version: '3.8'
services:
    oai-gnb:
        image: oaisoftwarealliance/oai-gnb-update
        expose:
            - 4043/tcp
            - 8080/tcp
            - 38412/sctp
        privileged: true
        container_name: rfsim5g-oai-gnb
        environment: 
            RFSIMULATOR: server
            USE_ADDITIONAL_OPTIONS: --sa -E --rfsim --log_config.global_log_options level,nocolor,time --opt.type pcap --opt.path /home/pcap.pcap
        volumes:
            - ./ran-conf/gnb.conf:/opt/oai-gnb/etc/gnb.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.153
            public_net_access:
                ipv4_address: 192.168.72.153
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-nr-ue1:
        image: oaisoftwarealliance/oai-nr-ue1
        privileged: true
        container_name: rfsim5g-oai-nr-ue1
        environment: 
            FSIMULATOR: 192.168.70.153
            USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 -C 3619200000 --nokrnmod --log_config.global_log_options level,nocolor,time --opt.type pcap --opt.path /home/pcap.pcap
        depends_on:
            - oai-gnb
        volumes:
            - ./ran-conf/nr-ue1.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.154
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
                        
    oai-nr-ue2:
        image: oaisoftwarealliance/oai-nr-ue2
        privileged: true
        container_name: rfsim5g-oai-nr-ue2
        environment: 
            RFSIMULATOR: 192.168.70.153
            USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 -C 3619200000 --log_config.global_log_options level,nocolor,time --opt.type pcap --opt.path /home/pcap.pcap
        depends_on:
            - oai-gnb
        volumes:
            - ./ran-conf/nr-ue2.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.155
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
networks:
    public_net:
        external:
            name: demo-oai-public-net
    public_net_access:
        external:
            name: oai-public-access
